Create Address repository
MilosSlavic/sedc-csharp-basics pull request #64
Opened 2021-05-30 19:45 UTC by Excession27

2021-05-30 19:55 UTC, Excession27 commented
Changed a typo in EmployeeDetailsRepository

2021-05-31 07:25 UTC, MilosSlavic requested changes

2021-05-31 07:25 UTC, MilosSlavic commented on CSharpBasics/CSB.Repository/Interfaces/IAddressRepository.cs
> +    public interface IAddressRepository
Nasledi generic repo

2021-05-31 07:25 UTC, MilosSlavic commented on CSharpBasics/CSB.Repository/Impl/AddressRepository.cs
> +    internal class AddressRepository : IAddressRepository
Nasledi generic repo

2021-05-31 07:25 UTC, MilosSlavic commented on CSharpBasics/CSB.Repository/Impl/AddressRepository.cs
> +        private FileDbProvider _fileDb;
Izbaci file db provider

2021-05-31 07:25 UTC, MilosSlavic commented on CSharpBasics/CSB.Repository/Impl/AddressRepository.cs
> +            return _fileDb.Addresses.Where(x => x.EmployeeId == employeeId).ToList();
koristi dbContext.Addresses

2021-05-31 07:25 UTC, MilosSlavic commented on CSharpBasics/CSB.Repository/Impl/AddressRepository.cs
> +        {
koristi dbContext.Addresses

2021-05-31 15:29 UTC, Excession27 commented
dbContext

2021-06-01 07:08 UTC, MilosSlavic approved these changes

2021-06-01 07:08 UTC, MilosSlavic commented on CSharpBasics/CSB.Repository/Impl/AddressRepository.cs
> +        public int AddAddress(Address address)
Ukloni AddAddress

2021-06-01 07:08 UTC, MilosSlavic commented on CSharpBasics/CSB.Repository/Entities/BaseEntity.cs
> +using CSB.Repository.Entities;
Ukloni using

2021-06-01 07:09 UTC, MilosSlavic approved these changes

2021-06-01 07:12 UTC, merged